/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, ChatBot as PrismaChatBot } from "@prisma/client";

export class ChatBotServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ChatBotCountArgs, "select">): Promise<number> {
    return this.prisma.chatBot.count(args);
  }

  async chatBots(args: Prisma.ChatBotFindManyArgs): Promise<PrismaChatBot[]> {
    return this.prisma.chatBot.findMany(args);
  }
  async chatBot(
    args: Prisma.ChatBotFindUniqueArgs
  ): Promise<PrismaChatBot | null> {
    return this.prisma.chatBot.findUnique(args);
  }
  async createChatBot(args: Prisma.ChatBotCreateArgs): Promise<PrismaChatBot> {
    return this.prisma.chatBot.create(args);
  }
  async updateChatBot(args: Prisma.ChatBotUpdateArgs): Promise<PrismaChatBot> {
    return this.prisma.chatBot.update(args);
  }
  async deleteChatBot(args: Prisma.ChatBotDeleteArgs): Promise<PrismaChatBot> {
    return this.prisma.chatBot.delete(args);
  }
}
