/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PaymentIntent } from "./PaymentIntent";
import { PaymentIntentCountArgs } from "./PaymentIntentCountArgs";
import { PaymentIntentFindManyArgs } from "./PaymentIntentFindManyArgs";
import { PaymentIntentFindUniqueArgs } from "./PaymentIntentFindUniqueArgs";
import { CreatePaymentIntentArgs } from "./CreatePaymentIntentArgs";
import { UpdatePaymentIntentArgs } from "./UpdatePaymentIntentArgs";
import { DeletePaymentIntentArgs } from "./DeletePaymentIntentArgs";
import { Invoice } from "../../invoice/base/Invoice";
import { PaymentIntentService } from "../paymentIntent.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PaymentIntent)
export class PaymentIntentResolverBase {
  constructor(
    protected readonly service: PaymentIntentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "read",
    possession: "any",
  })
  async _paymentIntentsMeta(
    @graphql.Args() args: PaymentIntentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PaymentIntent])
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "read",
    possession: "any",
  })
  async paymentIntents(
    @graphql.Args() args: PaymentIntentFindManyArgs
  ): Promise<PaymentIntent[]> {
    return this.service.paymentIntents(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PaymentIntent, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "read",
    possession: "own",
  })
  async paymentIntent(
    @graphql.Args() args: PaymentIntentFindUniqueArgs
  ): Promise<PaymentIntent | null> {
    const result = await this.service.paymentIntent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PaymentIntent)
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "create",
    possession: "any",
  })
  async createPaymentIntent(
    @graphql.Args() args: CreatePaymentIntentArgs
  ): Promise<PaymentIntent> {
    return await this.service.createPaymentIntent({
      ...args,
      data: {
        ...args.data,

        invoice: args.data.invoice
          ? {
              connect: args.data.invoice,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PaymentIntent)
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "update",
    possession: "any",
  })
  async updatePaymentIntent(
    @graphql.Args() args: UpdatePaymentIntentArgs
  ): Promise<PaymentIntent | null> {
    try {
      return await this.service.updatePaymentIntent({
        ...args,
        data: {
          ...args.data,

          invoice: args.data.invoice
            ? {
                connect: args.data.invoice,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PaymentIntent)
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "delete",
    possession: "any",
  })
  async deletePaymentIntent(
    @graphql.Args() args: DeletePaymentIntentArgs
  ): Promise<PaymentIntent | null> {
    try {
      return await this.service.deletePaymentIntent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Invoice, {
    nullable: true,
    name: "invoice",
  })
  @nestAccessControl.UseRoles({
    resource: "Invoice",
    action: "read",
    possession: "any",
  })
  async getInvoice(
    @graphql.Parent() parent: PaymentIntent
  ): Promise<Invoice | null> {
    const result = await this.service.getInvoice(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
