/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PaymentIntentService } from "../paymentIntent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaymentIntentCreateInput } from "./PaymentIntentCreateInput";
import { PaymentIntent } from "./PaymentIntent";
import { PaymentIntentFindManyArgs } from "./PaymentIntentFindManyArgs";
import { PaymentIntentWhereUniqueInput } from "./PaymentIntentWhereUniqueInput";
import { PaymentIntentUpdateInput } from "./PaymentIntentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaymentIntentControllerBase {
  constructor(
    protected readonly service: PaymentIntentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaymentIntent })
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPaymentIntent(
    @common.Body() data: PaymentIntentCreateInput
  ): Promise<PaymentIntent> {
    return await this.service.createPaymentIntent({
      data: {
        ...data,

        invoice: data.invoice
          ? {
              connect: data.invoice,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        amount: true,
        stripePaymentIntentId: true,

        invoice: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PaymentIntent] })
  @ApiNestedQuery(PaymentIntentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentIntents(
    @common.Req() request: Request
  ): Promise<PaymentIntent[]> {
    const args = plainToClass(PaymentIntentFindManyArgs, request.query);
    return this.service.paymentIntents({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        amount: true,
        stripePaymentIntentId: true,

        invoice: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaymentIntent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentIntent(
    @common.Param() params: PaymentIntentWhereUniqueInput
  ): Promise<PaymentIntent | null> {
    const result = await this.service.paymentIntent({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        amount: true,
        stripePaymentIntentId: true,

        invoice: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaymentIntent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePaymentIntent(
    @common.Param() params: PaymentIntentWhereUniqueInput,
    @common.Body() data: PaymentIntentUpdateInput
  ): Promise<PaymentIntent | null> {
    try {
      return await this.service.updatePaymentIntent({
        where: params,
        data: {
          ...data,

          invoice: data.invoice
            ? {
                connect: data.invoice,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,
          amount: true,
          stripePaymentIntentId: true,

          invoice: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaymentIntent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaymentIntent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePaymentIntent(
    @common.Param() params: PaymentIntentWhereUniqueInput
  ): Promise<PaymentIntent | null> {
    try {
      return await this.service.deletePaymentIntent({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,
          amount: true,
          stripePaymentIntentId: true,

          invoice: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
