/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ConversationFlowService } from "../conversationFlow.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ConversationFlowCreateInput } from "./ConversationFlowCreateInput";
import { ConversationFlow } from "./ConversationFlow";
import { ConversationFlowFindManyArgs } from "./ConversationFlowFindManyArgs";
import { ConversationFlowWhereUniqueInput } from "./ConversationFlowWhereUniqueInput";
import { ConversationFlowUpdateInput } from "./ConversationFlowUpdateInput";
import { FlowStepFindManyArgs } from "../../flowStep/base/FlowStepFindManyArgs";
import { FlowStep } from "../../flowStep/base/FlowStep";
import { FlowStepWhereUniqueInput } from "../../flowStep/base/FlowStepWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ConversationFlowControllerBase {
  constructor(
    protected readonly service: ConversationFlowService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ConversationFlow })
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createConversationFlow(
    @common.Body() data: ConversationFlowCreateInput
  ): Promise<ConversationFlow> {
    return await this.service.createConversationFlow({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ConversationFlow] })
  @ApiNestedQuery(ConversationFlowFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async conversationFlows(
    @common.Req() request: Request
  ): Promise<ConversationFlow[]> {
    const args = plainToClass(ConversationFlowFindManyArgs, request.query);
    return this.service.conversationFlows({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ConversationFlow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async conversationFlow(
    @common.Param() params: ConversationFlowWhereUniqueInput
  ): Promise<ConversationFlow | null> {
    const result = await this.service.conversationFlow({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ConversationFlow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateConversationFlow(
    @common.Param() params: ConversationFlowWhereUniqueInput,
    @common.Body() data: ConversationFlowUpdateInput
  ): Promise<ConversationFlow | null> {
    try {
      return await this.service.updateConversationFlow({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ConversationFlow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteConversationFlow(
    @common.Param() params: ConversationFlowWhereUniqueInput
  ): Promise<ConversationFlow | null> {
    try {
      return await this.service.deleteConversationFlow({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/flowSteps")
  @ApiNestedQuery(FlowStepFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FlowStep",
    action: "read",
    possession: "any",
  })
  async findFlowSteps(
    @common.Req() request: Request,
    @common.Param() params: ConversationFlowWhereUniqueInput
  ): Promise<FlowStep[]> {
    const query = plainToClass(FlowStepFindManyArgs, request.query);
    const results = await this.service.findFlowSteps(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        order: true,
        typeField: true,
        content: true,

        conversationFlow: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/flowSteps")
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "update",
    possession: "any",
  })
  async connectFlowSteps(
    @common.Param() params: ConversationFlowWhereUniqueInput,
    @common.Body() body: FlowStepWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flowSteps: {
        connect: body,
      },
    };
    await this.service.updateConversationFlow({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/flowSteps")
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "update",
    possession: "any",
  })
  async updateFlowSteps(
    @common.Param() params: ConversationFlowWhereUniqueInput,
    @common.Body() body: FlowStepWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flowSteps: {
        set: body,
      },
    };
    await this.service.updateConversationFlow({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/flowSteps")
  @nestAccessControl.UseRoles({
    resource: "ConversationFlow",
    action: "update",
    possession: "any",
  })
  async disconnectFlowSteps(
    @common.Param() params: ConversationFlowWhereUniqueInput,
    @common.Body() body: FlowStepWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      flowSteps: {
        disconnect: body,
      },
    };
    await this.service.updateConversationFlow({
      where: params,
      data,
      select: { id: true },
    });
  }
}
