/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Venta } from "./Venta";
import { VentaCountArgs } from "./VentaCountArgs";
import { VentaFindManyArgs } from "./VentaFindManyArgs";
import { VentaFindUniqueArgs } from "./VentaFindUniqueArgs";
import { DeleteVentaArgs } from "./DeleteVentaArgs";
import { VentaService } from "../venta.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Venta)
export class VentaResolverBase {
  constructor(
    protected readonly service: VentaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Venta",
    action: "read",
    possession: "any",
  })
  async _ventasMeta(
    @graphql.Args() args: VentaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Venta])
  @nestAccessControl.UseRoles({
    resource: "Venta",
    action: "read",
    possession: "any",
  })
  async ventas(@graphql.Args() args: VentaFindManyArgs): Promise<Venta[]> {
    return this.service.ventas(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Venta, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Venta",
    action: "read",
    possession: "own",
  })
  async venta(
    @graphql.Args() args: VentaFindUniqueArgs
  ): Promise<Venta | null> {
    const result = await this.service.venta(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Venta)
  @nestAccessControl.UseRoles({
    resource: "Venta",
    action: "delete",
    possession: "any",
  })
  async deleteVenta(
    @graphql.Args() args: DeleteVentaArgs
  ): Promise<Venta | null> {
    try {
      return await this.service.deleteVenta(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
