/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Cliente } from "./Cliente";
import { ClienteCountArgs } from "./ClienteCountArgs";
import { ClienteFindManyArgs } from "./ClienteFindManyArgs";
import { ClienteFindUniqueArgs } from "./ClienteFindUniqueArgs";
import { DeleteClienteArgs } from "./DeleteClienteArgs";
import { ClienteService } from "../cliente.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Cliente)
export class ClienteResolverBase {
  constructor(
    protected readonly service: ClienteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Cliente",
    action: "read",
    possession: "any",
  })
  async _clientesMeta(
    @graphql.Args() args: ClienteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Cliente])
  @nestAccessControl.UseRoles({
    resource: "Cliente",
    action: "read",
    possession: "any",
  })
  async clientes(
    @graphql.Args() args: ClienteFindManyArgs
  ): Promise<Cliente[]> {
    return this.service.clientes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Cliente, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Cliente",
    action: "read",
    possession: "own",
  })
  async cliente(
    @graphql.Args() args: ClienteFindUniqueArgs
  ): Promise<Cliente | null> {
    const result = await this.service.cliente(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Cliente)
  @nestAccessControl.UseRoles({
    resource: "Cliente",
    action: "delete",
    possession: "any",
  })
  async deleteCliente(
    @graphql.Args() args: DeleteClienteArgs
  ): Promise<Cliente | null> {
    try {
      return await this.service.deleteCliente(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
