/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Suscripcion } from "./Suscripcion";
import { SuscripcionCountArgs } from "./SuscripcionCountArgs";
import { SuscripcionFindManyArgs } from "./SuscripcionFindManyArgs";
import { SuscripcionFindUniqueArgs } from "./SuscripcionFindUniqueArgs";
import { DeleteSuscripcionArgs } from "./DeleteSuscripcionArgs";
import { SuscripcionService } from "../suscripcion.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Suscripcion)
export class SuscripcionResolverBase {
  constructor(
    protected readonly service: SuscripcionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Suscripcion",
    action: "read",
    possession: "any",
  })
  async _suscripcionsMeta(
    @graphql.Args() args: SuscripcionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Suscripcion])
  @nestAccessControl.UseRoles({
    resource: "Suscripcion",
    action: "read",
    possession: "any",
  })
  async suscripcions(
    @graphql.Args() args: SuscripcionFindManyArgs
  ): Promise<Suscripcion[]> {
    return this.service.suscripcions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Suscripcion, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Suscripcion",
    action: "read",
    possession: "own",
  })
  async suscripcion(
    @graphql.Args() args: SuscripcionFindUniqueArgs
  ): Promise<Suscripcion | null> {
    const result = await this.service.suscripcion(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Suscripcion)
  @nestAccessControl.UseRoles({
    resource: "Suscripcion",
    action: "delete",
    possession: "any",
  })
  async deleteSuscripcion(
    @graphql.Args() args: DeleteSuscripcionArgs
  ): Promise<Suscripcion | null> {
    try {
      return await this.service.deleteSuscripcion(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
